//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppJohn.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsJohn
    {
        public int ID { get; set; }
        public string product_name { get; set; }
        public string sku { get; set; }
        public decimal price { get; set; }
    }
}
